export const cities = [
  {
    province: "Anhui",
    cities: [
      "Anqing",
      "Bengbu",
      "Hefei",
      "Huainan",
      "Huangshan",
      "Ma’anshan",
      "Shexian",
      "Tongcheng",
      "Tongling",
      "Wuhu",
      "Xuancheng",
    ],
  },
  {
    province: "Beijing",
    cities: ["Beijing"],
  },
  {
    province: "Chongqing",
    cities: ["Chongqing", "Hechuan", "Wanzhou"],
  },
  {
    province: "Hebei",
    cities: [
      "Baoding",
      "Cangzhou",
      "Chengde",
      "Handan",
      "Kalgan",
      "Qinhuangdao",
      "Shanhaiguan",
      "Shijiazhuang",
      "Tangshan",
      "Xingtai",
      "Xuanhua",
      "Zhengding",
    ],
  },
  {
    province: "Hainan",
    cities: ["Haikou", "Sanya"],
  },
  {
    province: "Guizhou",
    cities: ["Anshun", "Duyun", "Guiyang", "Zunyi"],
  },

  {
    province: "Liaoning",
    cities: [
      "Anshan",
      "Beipiao",
      "Benxi",
      "Dalian",
      "Dandong",
      "Fushun",
      "Fuxin",
      "Jinzhou (southern Liaoning)",
      "Jinzhou (western Liaoning)",
      "Liaoyang",
      "Lüshun",
      "Shenyang",
      "Wafangdian",
      "Yingkou",
    ],
  },
  {
    province: "Hong Kong",
    cities: ["Hong Kong", "Victoria"],
  },
  {
    province: "Heilongjiang",
    cities: [
      "Acheng",
      "Binxian",
      "Harbin",
      "Hegang",
      "Hulan",
      "Jiamusi",
      "Jixi",
      "Mudanjiang",
      "Qiqihar",
      "Shuangyashan",
      "Yichun",
    ],
  },

  // {
  //   province: "",
  //   cities: [],
  // },
  // {
  //   province: "",
  //   cities: [],
  // },
  // "Hunan (Province)",
  // "Changde",
  // "Changsha",
  // "Hengyang",
  // "Jinshi",
  // "Shaoyang",
  // "Xiangtan",
  // "Yiyang",
  // "Yueyang",
  // "Zhuzhou",
  // "Inner Mongolia (Autonomous Region)",
  // "Baotou",
  // "Chifeng",
  // "Duolun",
  // "Erenhot",
  // "Hailar",
  // "Hohhot",
  // "Jining",
  // "Manzhouli",
  // "Tongliao",
  // "Jiangsu (Province)",
  // "Changshu",
  // "Changzhou",
  // "Huai’an",
  // "Huaiyin",
  // "Lianyungang",
  // "Nanjing",
  // "Nantong",
  // "Suzhou",
  // "Taizhou",
  // "Wuxi",
  // "Xuzhou",
  // "Yancheng",
  // "Yangzhou",
  // "Zhenjiang",
  // "Jiangxi (Province)",
  // "Ganzhou",
  // "Ji’an",
  // "Jingdezhen",
  // "Jiujiang",
  // "Nanchang",
  // "Pingxiang",
  // "Shangrao",
  // "Zhangshu",
  // "Jilin (Province)",
  // "Baicheng",
  // "Changchun",
  // "Jilin",
  // "Liaoyuan",
  // "Siping",
  // "Tonghua",
  // "Yanji",

  // "Macau (Special Administrative Region)",
  // "Macau",
  // "Ningxia (Autonomous Region)",
  // "Yinchuan",
  {
    province: "Shanxi",
    cities: [
      "Changzhi",
      "Datong",
      "Jinzhong",
      "Linfen",
      "Puzhou",
      "Taiyuan",
      "Yangquan",
    ],
  },
  {
    province: "Shanghai",
    cities: ["Shanghai"],
  },
  {
    province: "Shaanxi",
    cities: [
      "Ankang",
      "Baoji",
      "Hanzhong",
      "Shangluo",
      "Tongguan",
      "Xi’an",
      "Xianyang",
      "Yan’an",
    ],
  },
  {
    province: "Qinghai",
    cities: ["Golmud", "Lenghu", "Xining"],
  },

  {
    province: "Yunnan",
    cities: ["Dali", "Gejiu", "Jinghong", "Kaiyuan", "Kunming", "Pu’er"],
  },
  {
    province: "Tibet",
    cities: ["Gartok", "Gyangzê", "Lhasa", "Xigazê"],
  },
  {
    province: "Tianjin",
    cities: ["Tanggu", "Tianjin"],
  },
  {
    province: "Xinjiang",
    cities: [
      "Hami",
      "Hotan",
      "Karamay",
      "Kashgar",
      "Kucha",
      "Kuldja",
      "Shihezi",
      "Turfan",
      "Ürümqi",
      "Yarkand",
    ],
  },
  {
    province: "Guangxi",
    cities: [
      "Baise",
      "Beihai",
      "Guilin",
      "Liuzhou",
      "Nanning",
      "Pingxiang",
      "Wuzhou",
      "Yulin",
    ],
  },
  {
    province: "Shandong",
    cities: [
      "Dezhou",
      "Jinan",
      "Jining",
      "Linzi",
      "Qingdao",
      "Qufu",
      "Weifang",
      "Weihai",
      "Yantai",
      "Zaozhuang",
      "Zibo",
    ],
  },
  {
    province: "Zhejiang",
    cities: [
      "Fenghua",
      "Hangzhou",
      "Huzhou",
      "Jiaxing",
      "Jinhua",
      "Ningbo",
      "Quzhou",
      "Shaoxing",
      "Wenzhou",
    ],
  },
  {
    province: "Sichuan",
    cities: [
      "Chengdu",
      "Kangding",
      "Luzhou",
      "Mianyang",
      "Nanchong",
      "Neijiang",
      "Wutongqiao",
      "Ya’an",
      "Yibin",
      "Zigong",
    ],
  },
  {
    province: "Hubei",
    cities: [
      "Daye",
      "Hankou",
      "Hanyang",
      "Huangshi",
      "Jingzhou",
      "Laohekou",
      "Wuchang",
      "Wuhan",
      "Xiangfan",
      "Yichang",
    ],
  },
  {
    province: "Henan",
    cities: [
      "Anyang",
      "Hebi",
      "Jiaozuo",
      "Kaifeng",
      "Luohe",
      "Luoyang",
      "Nanyang",
      "Shangqiu",
      "Xinxiang",
      "Xinyang",
      "Xuchang",
      "Zhengzhou",
      "Zhoukou",
    ],
  },
  {
    province: "Guangdong",
    cities: [
      "Chaozhou",
      "Foshan",
      "Guangzhou",
      "Jiangmen",
      "Maoming",
      "Meizhou",
      "Shantou",
      "Shaoguan",
      "Shenzhen",
      "Zhanjiang",
      "Zhaoqing",
      "Zhongshan",
    ],
  },
  {
    province: "Gansu",
    cities: [
      "Dunhuang",
      "Jiuquan",
      "Lanzhou",
      "Pingliang",
      "Tianshui",
      "Wuwei",
      "Yumen",
    ],
  },

  {
    province: "Fujian",
    cities: [
      "Fuzhou",
      "Longyan",
      "Nanping",
      "Quanzhou",
      "Sanming",
      "Shaowu",
      "Xiamen",
      "Yong’an",
      "Zhangzhou",
    ],
  },
];

export const citiesArray = [
  "Anhui ()",
  "Anqing",
  "Bengbu",
  "Hefei",
  "Huainan",
  "Huangshan",
  "Ma’anshan",
  "Shexian",
  "Tongcheng",
  "Tongling",
  "Wuhu",
  "Xuancheng",
  "Beijing ()",
  "Beijing",
  "Chongqing ()",
  "Chongqing",
  "Hechuan",
  "Wanzhou",
  "Hebei ()",
  "Baoding",
  "Cangzhou",
  "Chengde",
  "Handan",
  "Kalgan",
  "Qinhuangdao",
  "Shanhaiguan",
  "Shijiazhuang",
  "Tangshan",
  "Xingtai",
  "Xuanhua",
  "Zhengding",
  "Hainan ()",
  "Haikou",
  "Sanya",
  "Guizhou ()",
  "Anshun",
  "Duyun",
  "Guiyang",
  "Zunyi",
  "Liaoning ()",
  "Anshan",
  "Beipiao",
  "Benxi",
  "Dalian",
  "Dandong",
  "Fushun",
  "Fuxin",
  "Jinzhou (southern Liaoning)",
  "Jinzhou (western Liaoning)",
  "Liaoyang",
  "Lüshun",
  "Shenyang",
  "Wafangdian",
  "Yingkou",
  "Hong Kong ()",
  "Hong Kong",
  "Victoria",
  "Heilongjiang ()",
  "Acheng",
  "Binxian",
  "Harbin",
  "Hegang",
  "Hulan",
  "Jiamusi",
  "Jixi",
  "Mudanjiang",
  "Qiqihar",
  "Shuangyashan",
  "Yichun",
  "Shanxi ()",
  "Changzhi",
  "Datong",
  "Jinzhong",
  "Linfen",
  "Puzhou",
  "Taiyuan",
  "Yangquan",
  "Shanghai ()",
  "Shanghai",
  "Shaanxi ()",
  "Ankang",
  "Baoji",
  "Hanzhong",
  "Shangluo",
  "Tongguan",
  "Xi’an",
  "Xianyang",
  "Yan’an",
  "Qinghai ()",
  "Golmud",
  "Lenghu",
  "Xining",
  "Yunnan ()",
  "Dali",
  "Gejiu",
  "Jinghong",
  "Kaiyuan",
  "Kunming",
  "Pu’er",
  "Tibet ()",
  "Gartok",
  "Gyangzê",
  "Lhasa",
  "Xigazê",
  "Tianjin ()",
  "Tanggu",
  "Tianjin",
  "Xinjiang ()",
  "Hami",
  "Hotan",
  "Karamay",
  "Kashgar",
  "Kucha",
  "Kuldja",
  "Shihezi",
  "Turfan",
  "Ürümqi",
  "Yarkand",
  "Guangxi ()",
  "Baise",
  "Beihai",
  "Guilin",
  "Liuzhou",
  "Nanning",
  "Pingxiang",
  "Wuzhou",
  "Yulin",
  "Shandong ()",
  "Dezhou",
  "Jinan",
  "Jining",
  "Linzi",
  "Qingdao",
  "Qufu",
  "Weifang",
  "Weihai",
  "Yantai",
  "Zaozhuang",
  "Zibo",
  "Zhejiang ()",
  "Fenghua",
  "Hangzhou",
  "Huzhou",
  "Jiaxing",
  "Jinhua",
  "Ningbo",
  "Quzhou",
  "Shaoxing",
  "Wenzhou",
  "Sichuan ()",
  "Chengdu",
  "Kangding",
  "Luzhou",
  "Mianyang",
  "Nanchong",
  "Neijiang",
  "Wutongqiao",
  "Ya’an",
  "Yibin",
  "Zigong",
  "Hubei ()",
  "Daye",
  "Hankou",
  "Hanyang",
  "Huangshi",
  "Jingzhou",
  "Laohekou",
  "Wuchang",
  "Wuhan",
  "Xiangfan",
  "Yichang",
  "Henan ()",
  "Anyang",
  "Hebi",
  "Jiaozuo",
  "Kaifeng",
  "Luohe",
  "Luoyang",
  "Nanyang",
  "Shangqiu",
  "Xinxiang",
  "Xinyang",
  "Xuchang",
  "Zhengzhou",
  "Zhoukou",
  "Guangdong ()",
  "Chaozhou",
  "Foshan",
  "Guangzhou",
  "Jiangmen",
  "Maoming",
  "Meizhou",
  "Shantou",
  "Shaoguan",
  "Shenzhen",
  "Zhanjiang",
  "Zhaoqing",
  "Zhongshan",
  "Gansu ()",
  "Dunhuang",
  "Jiuquan",
  "Lanzhou",
  "Pingliang",
  "Tianshui",
  "Wuwei",
  "Yumen",
  "Fujian ()",
  "Fuzhou",
  "Longyan",
  "Nanping",
  "Quanzhou",
  "Sanming",
  "Shaowu",
  "Xiamen",
  "Yong’an",
  "Zhangzhou",
];
