export const cities = [
  "Anhui (Province)",
  "Anqing",
  "Bengbu",
  "Hefei",
  "Huainan",
  "Huangshan",
  "Ma’anshan",
  "Shexian",
  "Tongcheng",
  "Tongling",
  "Wuhu",
  "Xuancheng",
  "Beijing (Provincial-Level Municipality, Capital)",
  "Beijing",
  "Chongqing (Provincial-Level Municipality)",
  "Chongqing",
  "Hechuan",
  "Wanzhou",
  "Fujian (Province)",
  "Fuzhou",
  "Longyan",
  "Nanping",
  "Quanzhou",
  "Sanming",
  "Shaowu",
  "Xiamen",
  "Yong’an",
  "Zhangzhou",
  "Gansu (Province)",
  "Dunhuang",
  "Jiuquan",
  "Lanzhou",
  "Pingliang",
  "Tianshui",
  "Wuwei",
  "Yumen",
  "Guangdong (Province)",
  "Chaozhou",
  "Foshan",
  "Guangzhou",
  "Jiangmen",
  "Maoming",
  "Meizhou",
  "Shantou",
  "Shaoguan",
  "Shenzhen",
  "Zhanjiang",
  "Zhaoqing",
  "Zhongshan",
  "Guangxi (Autonomous Region)",
  "Baise",
  "Beihai",
  "Guilin",
  "Liuzhou",
  "Nanning",
  "Pingxiang",
  "Wuzhou",
  "Yulin",
  "Guizhou (Province)",
  "Anshun",
  "Duyun",
  "Guiyang",
  "Zunyi",
  "Hainan (Province)",
  "Haikou",
  "Hebei (Province)",
  "Baoding",
  "Cangzhou",
  "Chengde",
  "Handan",
  "Kalgan",
  "Qinhuangdao",
  "Shanhaiguan",
  "Shijiazhuang",
  "Tangshan",
  "Xingtai",
  "Xuanhua",
  "Zhengding",
  "Heilongjiang (Province)",
  "Acheng",
  "Binxian",
  "Harbin",
  "Hegang",
  "Hulan",
  "Jiamusi",
  "Jixi",
  "Mudanjiang",
  "Qiqihar",
  "Shuangyashan",
  "Yichun",
  "Henan (Province)",
  "Anyang",
  "Hebi",
  "Jiaozuo",
  "Kaifeng",
  "Luohe",
  "Luoyang",
  "Nanyang",
  "Shangqiu",
  "Xinxiang",
  "Xinyang",
  "Xuchang",
  "Zhengzhou",
  "Zhoukou",
  "Hong Kong (Special Administrative Region)",
  "Hong Kong",
  "Victoria",
  "Hubei (Province)",
  "Daye",
  "Hankou",
  "Hanyang",
  "Huangshi",
  "Jingzhou",
  "Laohekou",
  "Wuchang",
  "Wuhan",
  "Xiangfan",
  "Yichang",
  "Hunan (Province)",
  "Changde",
  "Changsha",
  "Hengyang",
  "Jinshi",
  "Shaoyang",
  "Xiangtan",
  "Yiyang",
  "Yueyang",
  "Zhuzhou",
  "Inner Mongolia (Autonomous Region)",
  "Baotou",
  "Chifeng",
  "Duolun",
  "Erenhot",
  "Hailar",
  "Hohhot",
  "Jining",
  "Manzhouli",
  "Tongliao",
  "Jiangsu (Province)",
  "Changshu",
  "Changzhou",
  "Huai’an",
  "Huaiyin",
  "Lianyungang",
  "Nanjing",
  "Nantong",
  "Suzhou",
  "Taizhou",
  "Wuxi",
  "Xuzhou",
  "Yancheng",
  "Yangzhou",
  "Zhenjiang",
  "Jiangxi (Province)",
  "Ganzhou",
  "Ji’an",
  "Jingdezhen",
  "Jiujiang",
  "Nanchang",
  "Pingxiang",
  "Shangrao",
  "Zhangshu",
  "Jilin (Province)",
  "Baicheng",
  "Changchun",
  "Jilin",
  "Liaoyuan",
  "Siping",
  "Tonghua",
  "Yanji",
  "Liaoning (Province)",
  "Anshan",
  "Beipiao",
  "Benxi",
  "Dalian",
  "Dandong",
  "Fushun",
  "Fuxin",
  "Jinzhou (southern Liaoning)",
  "Jinzhou (western Liaoning)",
  "Liaoyang",
  "Lüshun",
  "Shenyang",
  "Wafangdian",
  "Yingkou",
  "Macau (Special Administrative Region)",
  "Macau",
  "Ningxia (Autonomous Region)",
  "Yinchuan",
  "Qinghai (Province)",
  "Golmud",
  "Lenghu",
  "Xining",
  "Shaanxi (Province)",
  "Ankang",
  "Baoji",
  "Hanzhong",
  "Shangluo",
  "Tongguan",
  "Xi’an",
  "Xianyang",
  "Yan’an",
  "Shandong (Province)",
  "Dezhou",
  "Jinan",
  "Jining",
  "Linzi",
  "Qingdao",
  "Qufu",
  "Weifang",
  "Weihai",
  "Yantai",
  "Zaozhuang",
  "Zibo",
  "Shanghai (Provincial-Level Municipality)",
  "Shanghai",
  "Shanxi (Province)",
  "Changzhi",
  "Datong",
  "Jinzhong",
  "Linfen",
  "Puzhou",
  "Taiyuan",
  "Yangquan",
  "Sichuan (Province)",
  "Chengdu",
  "Kangding",
  "Luzhou",
  "Mianyang",
  "Nanchong",
  "Neijiang",
  "Wutongqiao",
  "Ya’an",
  "Yibin",
  "Zigong",
  "Tianjin (Provincial-Level Municipality)",
  "Tanggu",
  "Tianjin",
  "Tibet (Autonomous Region)",
  "Gartok",
  "Gyangzê",
  "Lhasa",
  "Xigazê",
  "Xinjiang (Autonomous Region)",
  "Hami",
  "Hotan",
  "Karamay",
  "Kashgar",
  "Kucha",
  "Kuldja",
  "Shihezi",
  "Turfan",
  "Ürümqi",
  "Yarkand",
  "Yunnan (Province)",
  "Dali",
  "Gejiu",
  "Jinghong",
  "Kaiyuan",
  "Kunming",
  "Pu’er",
  "Zhejiang (Province)",
  "Fenghua",
  "Hangzhou",
  "Huzhou",
  "Jiaxing",
  "Jinhua",
  "Ningbo",
  "Quzhou",
  "Shaoxing",
  "Wenzhou",
];
